services:
  bot:
    build: .
    restart: unless-stopped
    volumes:
      - ./SKNIBot/DynamicDatabase.sqlite:${DYNAMIC_DB_PATH}
      - ./SKNIBot/StaticDatabase.sqlite:${STATIC_DB_PATH}
    env_file:
      - ./.env
